---
- hosts: localhost
  remote_user: root
  tasks:
  - name: Install Apache
    yum: name=httpd state=present
  - name: Install PHP PHP-MYSQL
    yum: name={{ item }} state=present
    with_items:
        - php
        - php-mysql
        - mysql
  - name: Set up wp-cli
    get_url:
        url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        dest: /usr/bin/wp
        mode: 0755
  - name: download wordpress
    command: wp core download
    args:
        chdir: /var/www/html
  - name: wordpress config
    command: wp core config --dbhost=wordpresrds.czrmpuv90e38.us-east-1.rds.amazonaws.com   --dbname=wpdata --dbuser=wpuser --dbpass=password --skip-check
    args:
        chdir: /var/www/html
  - name: Apache service
    service:
        name: httpd
        enabled: yes
  
