---
- hosts: localhost
  remote_user: root
  tasks:
  - name: Add html directory
    command: mkdir -p /var/www/html
  - name: download wordpress
    get_url:
        url: https://wordpress.org/wordpress-4.8.tar.gz
        dest: /tmp
        mode: 0755
  - name: place wordpres files
    unarchive:
        src: /tmp/wordpress-4.8.tar.gz
        dest: /var/www/html
  - file: /tmp/wordpress-4.8.tar.gz
    state: absent
  - name: wordpress ownership
    command: chown -R www-data:www-data /var/www/html
  - name: apache2 restart
    service:
        name: apache2
        state: restarted